eureka:
  instance:
    hostname: localhost
  client:
    preferIpAddress: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
springdoc:
  swagger-ui:
    urls:
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization
      - name: employee
        url: /v3/api-docs/employee

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include=health,info,beans:
