server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
