# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven for config-server
      run: mvn -B package --file config-server/pom.xml

    - name: Build with Maven for departement
      run: mvn -B package --file departement/pom.xml

    - name: Build with Maven for discovery
      run: mvn -B package --file discovery/pom.xml

    - name: Build with Maven for employee
      run: mvn -B package --file employee/pom.xml

    - name: Build with Maven for gateway
      run: mvn -B package --file gateway/pom.xml

    - name: Build with Maven for organization
      run: mvn -B package --file organization/pom.xml

    - name: Build with Maven for school
      run: mvn -B package --file school/pom.xml

    - name: Build with Maven for student
      run: mvn -B package --file student/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@4f64ddab9d742a4806eeb588d238e4c311a8397d
